name: Deploy to GitHub Pages

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4 # Updated to use version 4

    # Add steps for any build process you have here
    - name: unzip samples1.zip
      run: unzip samples/sample1.zip -d public/

    - name: unzip samples2.zip
      run: unzip samples/sample2.zip -d public/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages # The target branch for deployments
        publish_dir: ./public # The folder that you want to deploy
