name: Inspect Environment

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: List directory contents
        run: |
             ls -lt
             echo ${{ github.workspace }}
             echo $GITHUB_WORKSPACE	
