name: Deploy Zips to gh-pages

on:
  # Trigger on manual dispatch, you can also set other triggers
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out gh-pages branch
    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: List after first checkout
      run: ls -ltR

    # Step 2: Check out the zip files from the main branch
    - name: Checkout main for zip files
      uses: actions/checkout@v2
      with:
        ref: main
        path: 'main-content'

    - name: List after second checkout
      run: ls -ltR

    # Step 3: Unzip the files
    - name: Unzip files
      run: |
        unzip main-content/samples/sample1.zip -d samples/
        unzip main-content/samples/sample2.zip -d samples/

    - name: List after unzip checkout
      run: ls -ltR

#    # Optional: Step 4, if you need to move files around or further process them
#    - name: Move files
#      run: |
#        mv path/to/destination/somefile path/to/gh-pages-destination

    # Step 5: Commit and push changes to gh-pages
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy unzipped content to gh-pages" -a || echo "No changes to commit"
        git push origin gh-pages

